### ISSUE TITLE
排版问题复现> > https://wanpinhuan.github.io/blog.wanpinhuan.github.io 我的文章怎么都居中了，还有右上角的图标昨天好好的现在都看不见了，跟主题设置有关吗。

### ISSUE THREAD

**Issue by ricoeur** [Meekdai/meekdai.github.io#58]
截了图
![1719786749143](https://github.com/Meekdai/meekdai.github.io/assets/13033076/81cf483d-582e-4c73-9f0f-b50665b521c9)
![1719786732889](https://github.com/Meekdai/meekdai.github.io/assets/13033076/94538e2b-d6a9-407f-a056-2fff6175eb16)

              > > https://wanpinhuan.github.io/blog.wanpinhuan.github.io 我的文章怎么都居中了，还有右上角的图标昨天好好的现在都看不见了，跟主题设置有关吗。
> 
> @wanpinhuan 我现在看都是正常的啊？可以截图看一下。

额，今天在家里电脑上和手机上显示又是正常的，之前浏览器历史记录和cookies都清理过，真是搞不懂。

_Originally posted by @wanpinhuan in https://github.com/Meekdai/meekdai.github.io/issues/39#issuecomment-2184067135_

**Comment by Meekdai** [comment]
应该是primer.css没有正确加载，可能是Staticfile的CDN不是很好，后续打算更换。
