### ISSUE TITLE
您好，请教一个问题，标题跳转代码在blog里无反应该怎么解决？

### ISSUE THREAD

**Issue by DiYingisaDer** [Meekdai/meekdai.github.io#60]
您好，请教一个问题
我使用以下两种代码来实现页面的标题跳转，在Issue的预览界面成功进行跳转，可在Gmeek博客文章里却无效，请问该如何解决？

`<a href="#A01">A001</a>`
`<span id="A01">A001</span>`
和
`# A01`
`[A01](#A01)`

_Originally posted by @DiYingisaDer in https://github.com/Meekdai/meekdai.github.io/issues/39#issuecomment-2199876594_

**Comment by Meekdai** [comment]
请去Gmeek仓库提问题
